set(LIBZIP_SOURCE_DIR ${CMAKE_SOURCE_DIR}/thirdparty/libzip)
set(LIBZIP_BINARY_DIR ${CMAKE_BINARY_DIR}/libzip)

ExternalProject_Add(libzip_ext
	SOURCE_DIR "${LIBZIP_SOURCE_DIR}"
	CMAKE_ARGS -DCMAKE_INSTALL_PREFIX:PATH=${LIBZIP_BINARY_DIR} -DBUILD_DOC=OFF -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF -DCMAKE_POSITION_INDEPENDENT_CODE=ON
	# CMAKE_ARGS -DBUILD_DOC=OFF -DBUILD_EXAMPLES=OFF -DBUILD_SHARED_LIBS=OFF
	BUILD_BYPRODUCTS   ${LIBZIP_BINARY_DIR}/lib/libzip.a
)

file(MAKE_DIRECTORY ${LIBZIP_BINARY_DIR}/include)

add_library(LIBZIP STATIC IMPORTED GLOBAL)
target_include_directories(LIBZIP INTERFACE ${LIBZIP_BINARY_DIR}/include)
#target_link_libraries(LIBZIP INTERFACE "${libzip_ext_LIBRARIES}")
set_target_properties (LIBZIP PROPERTIES
	IMPORTED_LOCATION ${LIBZIP_BINARY_DIR}/lib/libzip.a
	INTERFACE_INCLUDE_DIRECTORIES ${LIBZIP_BINARY_DIR}/include)
add_dependencies(LIBZIP libzip_ext)
set(LIBZIP_FOUND true)
set(LIBZIP_VERSION "1.7.3")
add_library(PkgConfig::LIBZIP ALIAS LIBZIP)
